### ISSUE TITLE
Clarify library purpose

### ISSUE THREAD

**Issue by DimitryDushkin** [BrOrlandi/bigtext.js#1]
I spent 5 minutes to understand, that library can only work with one line text. Please mention on **bold** in description.

**Comment by BrOrlandi** [comment]
Hi @DimitryDushkin.

No, this lib works with multiple text lines, You can format it using HTML <br> tags.

Could you try it?

Thanks!

**Comment by BrOrlandi** [comment]
Closing as it has no feedback from reporter.

**Comment by Jetroid** [comment]
@BrOrlandi I actually agree with @DimitryDushkin - I switched from bigtext to textfill (http://jquery-textfill.github.io/example/) because I found that (if I did not add HTML tags, which wasn't feasible for my project as I didn't have control of the BigText'd content) bigtext would fill the text as big as it could be - but only one line. 

Whereas textfill makes the text *as big as it can possibly be*, including making it wrap to multiple lines.
